// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: addtask.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AddTaskToDBServiceClient is the client API for AddTaskToDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddTaskToDBServiceClient interface {
	AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error)
}

type addTaskToDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddTaskToDBServiceClient(cc grpc.ClientConnInterface) AddTaskToDBServiceClient {
	return &addTaskToDBServiceClient{cc}
}

func (c *addTaskToDBServiceClient) AddTask(ctx context.Context, in *AddTaskRequest, opts ...grpc.CallOption) (*AddTaskResponse, error) {
	out := new(AddTaskResponse)
	err := c.cc.Invoke(ctx, "/nextdate.AddTaskToDBService/AddTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddTaskToDBServiceServer is the server API for AddTaskToDBService service.
// All implementations must embed UnimplementedAddTaskToDBServiceServer
// for forward compatibility
type AddTaskToDBServiceServer interface {
	AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error)
	mustEmbedUnimplementedAddTaskToDBServiceServer()
}

// UnimplementedAddTaskToDBServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAddTaskToDBServiceServer struct {
}

func (UnimplementedAddTaskToDBServiceServer) AddTask(context.Context, *AddTaskRequest) (*AddTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTask not implemented")
}
func (UnimplementedAddTaskToDBServiceServer) mustEmbedUnimplementedAddTaskToDBServiceServer() {}

// UnsafeAddTaskToDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddTaskToDBServiceServer will
// result in compilation errors.
type UnsafeAddTaskToDBServiceServer interface {
	mustEmbedUnimplementedAddTaskToDBServiceServer()
}

func RegisterAddTaskToDBServiceServer(s grpc.ServiceRegistrar, srv AddTaskToDBServiceServer) {
	s.RegisterService(&AddTaskToDBService_ServiceDesc, srv)
}

func _AddTaskToDBService_AddTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddTaskToDBServiceServer).AddTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nextdate.AddTaskToDBService/AddTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddTaskToDBServiceServer).AddTask(ctx, req.(*AddTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddTaskToDBService_ServiceDesc is the grpc.ServiceDesc for AddTaskToDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddTaskToDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nextdate.AddTaskToDBService",
	HandlerType: (*AddTaskToDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTask",
			Handler:    _AddTaskToDBService_AddTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addtask.proto",
}
