// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: nextdate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NextDateServiceClient is the client API for NextDateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NextDateServiceClient interface {
	NextDate(ctx context.Context, in *NextDateRequest, opts ...grpc.CallOption) (*NextDateResponse, error)
}

type nextDateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNextDateServiceClient(cc grpc.ClientConnInterface) NextDateServiceClient {
	return &nextDateServiceClient{cc}
}

func (c *nextDateServiceClient) NextDate(ctx context.Context, in *NextDateRequest, opts ...grpc.CallOption) (*NextDateResponse, error) {
	out := new(NextDateResponse)
	err := c.cc.Invoke(ctx, "/nextdate.NextDateService/NextDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NextDateServiceServer is the server API for NextDateService service.
// All implementations must embed UnimplementedNextDateServiceServer
// for forward compatibility
type NextDateServiceServer interface {
	NextDate(context.Context, *NextDateRequest) (*NextDateResponse, error)
	mustEmbedUnimplementedNextDateServiceServer()
}

// UnimplementedNextDateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNextDateServiceServer struct {
}

func (UnimplementedNextDateServiceServer) NextDate(context.Context, *NextDateRequest) (*NextDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextDate not implemented")
}
func (UnimplementedNextDateServiceServer) mustEmbedUnimplementedNextDateServiceServer() {}

// UnsafeNextDateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NextDateServiceServer will
// result in compilation errors.
type UnsafeNextDateServiceServer interface {
	mustEmbedUnimplementedNextDateServiceServer()
}

func RegisterNextDateServiceServer(s grpc.ServiceRegistrar, srv NextDateServiceServer) {
	s.RegisterService(&NextDateService_ServiceDesc, srv)
}

func _NextDateService_NextDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NextDateServiceServer).NextDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nextdate.NextDateService/NextDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NextDateServiceServer).NextDate(ctx, req.(*NextDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NextDateService_ServiceDesc is the grpc.ServiceDesc for NextDateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NextDateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nextdate.NextDateService",
	HandlerType: (*NextDateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextDate",
			Handler:    _NextDateService_NextDate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nextdate.proto",
}
